# .lintstagedrc.yml

# Для файлов .ts, .tsx, .js — сначала запускаем eslint с автоисправлением, затем prettier
'*.{ts,tsx,js}':
  - 'eslint --cache --cache-location ./node_modules/.cache/.eslintcache --fix'
  - 'prettier --loglevel warn --cache --write'

# Для файлов .json, .yml, .scss — просто применяем prettier
'*.{json,yml}':
  - 'prettier --loglevel warn --cache --write'

'*.{scss}':
  - 'stylelint --fix'
  - 'prettier --loglevel warn --cache --write'
